META
{
  Parser = VFX;
};

INSTANCE spellFX_WaterRing_Tiny(CFx_Base_Proto)
{
  visname_S = "ZWATERRING_TINY";
  visAlpha = 1;
  emtrjmode_s = "FIXED";
};

INSTANCE spellFX_WaterRing_Small(CFx_Base_Proto)
{
  visname_S = "ZWATERRING_SMALL";
  visAlpha = 1;
  emtrjmode_s = "FIXED";
};

INSTANCE spellFX_WaterRing_Medium(CFx_Base_Proto)
{
  visname_S = "ZWATERRING_MEDIUM";
  visAlpha = 1;
  emtrjmode_s = "FIXED";
};

INSTANCE spellFX_WaterRing_Large(CFx_Base_Proto)
{
  visname_S = "ZWATERRING_LARGE";
  visAlpha = 1;
  emtrjmode_s = "FIXED";
};

INSTANCE spellFX_WaterSplash_Tiny(CFx_Base_Proto)
{
  visname_S = "PFX_WATERSPLASH_TINY";
  visAlpha = 1;
  emtrjmode_s = "FIXED";
};

INSTANCE spellFX_WaterSplash_Small(CFx_Base_Proto)
{
  visname_S = "PFX_WATERSPLASH_SMALL";
  visAlpha = 1;
  emtrjmode_s = "FIXED";
};

INSTANCE spellFX_WaterSplash_Medium(CFx_Base_Proto)
{
  visname_S = "PFX_WATERSPLASH_MEDIUM";
  visAlpha = 1;
  emtrjmode_s = "FIXED";
};

INSTANCE spellFX_WaterSplash_Large(CFx_Base_Proto)
{
  visname_S = "PFX_WATERSPLASH_LARGE";
  visAlpha = 1;
  emtrjmode_s = "FIXED";
};

INSTANCE spellFX_WaterSplash(CFx_Base_Proto)
{
  visname_S = "PFX_WATERSPLASH";
  visAlpha = 1;
  emtrjmode_s = "FIXED";
};

INSTANCE spellFX_WeaponSplash(CFx_Base_Proto)
{
  visname_S = "PFX_WEAPONSPLASH";
  visAlpha = 1;
  emtrjmode_s = "FIXED";
};